# Generated by Django 3.2.4 on 2021-06-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('catedescripcion', models.CharField(blank=True, max_length=60, null=True)),
                ('catetipo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('contraceña', models.CharField(max_length=40)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Local1',
            fields=[
                ('idlocal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('pasillo', models.IntegerField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'local1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('contraceña', models.CharField(max_length=40)),
                ('fechaalta', models.DateField(blank=True, null=True)),
                ('fechabaja', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locatario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('idorden', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadproductos', models.IntegerField(blank=True, null=True)),
                ('preciototal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('servicio', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpagos', models.AutoField(primary_key=True, serialize=False)),
                ('comisionporcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('comisionpesos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precioventa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('existencia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('numeroproductos', models.IntegerField(blank=True, null=True)),
                ('preciopromocion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'promocion',
                'managed': False,
            },
        ),
    ]
