# Generated by Django 2.2 on 2021-06-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('cateclave', models.IntegerField(primary_key=True, serialize=False)),
                ('catedescripcion', models.CharField(max_length=40)),
                ('catetipo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
    ]
