# Generated by Django 2.2 on 2021-06-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadoaplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('Idlocal', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Pasillo', models.IntegerField()),
                ('Zona', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('IdUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Contraceña', models.CharField(max_length=30)),
                ('FechaAlta', models.DateField()),
                ('FechaBaja', models.DateField(blank=True)),
                ('Status', models.IntegerField(help_text='Puede tomar el valor de Activo = 1 o Inactivo = 0')),
            ],
            options={
                'db_table': 'locatario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('IdOrden', models.IntegerField(primary_key=True, serialize=False)),
                ('CantidadProductos', models.IntegerField()),
                ('PrecioTotal', models.FloatField()),
                ('estado', models.IntegerField(help_text='Existen tres números 1=Entregado, 2=pendiente (a recoger o entregar) 3=recolectando')),
                ('servicio', models.CharField(help_text='Domicilio o recoleccion', max_length=15)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IdProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=40)),
                ('PrecioVenta', models.FloatField()),
                ('Existencia', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
